/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.ui;

import Operational.Checks;
import java.awt.Color;
import java.beans.PropertyVetoException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import model.dao.FacultyInfoDAO;
import model.to.FacultyInfoTO;

/**
 *
 * @author vijay
 */
public class AddFacultyInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddFacultyInfo
     */
    public AddFacultyInfo() {
        initComponents();
        setSize(645, 457);
        getRootPane().setDefaultButton(jbtnAddFacultyInfo);
        getContentPane().setBackground(Color.YELLOW);
    }

    public AddFacultyInfo(FacultyInfoTO data) {
        this();
        if (data != null) {
            jtfFacultyID.setText(data.getFacultyID());
            jtfFacultyName.setText(data.getFacultyName());
            jtfEmailID.setText(data.getEmailID());

            jtfFacultyID.setEditable(false);
            jbtnAddFacultyInfo.setText("Update Faculty Info");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfEmailID = new javax.swing.JTextField();
        jtfFacultyID = new javax.swing.JTextField();
        jtfFacultyName = new javax.swing.JTextField();
        jbtnAddFacultyInfo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Faculty Info");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Enter Email ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 190, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Enter Faculty ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 32, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Enter Faculty Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 170, 30);
        getContentPane().add(jtfEmailID);
        jtfEmailID.setBounds(260, 190, 290, 40);
        getContentPane().add(jtfFacultyID);
        jtfFacultyID.setBounds(260, 30, 290, 40);

        jtfFacultyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFacultyNameKeyTyped(evt);
            }
        });
        getContentPane().add(jtfFacultyName);
        jtfFacultyName.setBounds(260, 110, 290, 40);

        jbtnAddFacultyInfo.setBackground(new java.awt.Color(255, 153, 0));
        jbtnAddFacultyInfo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnAddFacultyInfo.setText("AddFacultyInfo");
        jbtnAddFacultyInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddFacultyInfoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAddFacultyInfo);
        jbtnAddFacultyInfo.setBounds(160, 270, 320, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddFacultyInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddFacultyInfoActionPerformed
        String message = "";
        try {

            String facultyid = jtfFacultyID.getText().trim();
            String facultyname = jtfFacultyName.getText().trim();
            String emailid = jtfEmailID.getText().trim();
            if (Checks.isEmpty(facultyid) && Checks.isEmpty(facultyname) && Checks.isEmpty(emailid)) {
                message = "Please Enter Some Value In The Empty Boxes";
            }else if(Checks.isEmpty(facultyid)){
                message = "Please Enter Some value in Faculty Id and Faculty Name(if not filled),Email(if not filled) Before pressing Add button...!";
            }else if(Checks.isEmpty(facultyname)){
                message = "Please Enter Some Value in Faculty Name and Faculty Id(if not filled), Email(if not filled) before pressing Add Button...!";
            }else if(Checks.isEmpty(emailid)){
                message = "Please Enter Some Value in Email and Faculty name(if not filled),Faculty id(if not filled) before proceeding further...!";
            }
            //else if (emailid.indexOf("@") == -1 || emailid.lastIndexOf(".") == -1 || (emailid.indexOf("@") > emailid.lastIndexOf("."))) {
            else if (!emailid.matches("^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z-0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$")) {
                message = "Invalid Format of EmailID";
            } else {
                FacultyInfoTO data = new FacultyInfoTO();
                data.setFacultyID(facultyid);
                data.setFacultyName(facultyname);
                data.setEmailID(emailid);
                FacultyInfoDAO action = new FacultyInfoDAO();
                if (jbtnAddFacultyInfo.getText().contains("Add")) {
                    if (action.insertRecord(data)) {
                        message = "Record Is Successfully Added";
                    } else {
                        message = action.geterrorMessage();
                        if (message.contains("PRIMARY")) {
                            message = "This FacultyID Is Already In Use";
                        }
                        if (message.contains("Duplicate")) {
                            message = "Hey User This Value Has Already Been Inserted So Please Enter Some Other Record!";
                        }
                    }
                } else if (jbtnAddFacultyInfo.getText().contains("Update")) {
                    if (action.updateRecord(data)) {
                        message = "Hey User Your Record Is Successfully Updated. Hope You Updated Your Record Carefully!";
                    } else {
                        message = action.geterrorMessage();
                    }

                    JOptionPane.showMessageDialog(this, message);
                    ViewFacultyInfo obj = new ViewFacultyInfo();
                    obj.setVisible(true);
                    JDesktopPane jdp = getDesktopPane();
                    jdp.add(obj);
                    try {
                        obj.setSelected(true);
                    } catch (PropertyVetoException ex) {
                    }
                    dispose();
                }
            }
        } catch (Exception ex) {
            message = ex.getMessage();
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_jbtnAddFacultyInfoActionPerformed

    private void jtfFacultyNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFacultyNameKeyTyped
        if (Character.isLetter(evt.getKeyChar()) || evt.getKeyChar() == ' ') {

        } else {
            evt.consume();
            try {

            } catch (Exception ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jtfFacultyNameKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnAddFacultyInfo;
    private javax.swing.JTextField jtfEmailID;
    private javax.swing.JTextField jtfFacultyID;
    private javax.swing.JTextField jtfFacultyName;
    // End of variables declaration//GEN-END:variables
}
