/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package admin.ui;

import Operational.Checks;
import java.awt.Color;
import java.beans.PropertyVetoException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import model.dao.RoomInfoDAO;
import model.to.RoomInfoTO;

/**
 *
 * @author vijay
 */
public class AddRoomInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddRoomInfo
     */
    public AddRoomInfo() {
        initComponents();
        setSize(684,450);
        getRootPane().setDefaultButton(jbtnAddRoomInfo);
        getContentPane().setBackground(Color.ORANGE);
    }
    
    public AddRoomInfo(RoomInfoTO data) {
        this();
        if(data!=null){
            jtfRoomID.setText(data.getRoomID());
            jtfRoomName.setText(data.getRoomName());
            jtfNoofChair.setText(String.valueOf(data.getNoofChair()));
            
            jtfRoomID.setEditable(false);
            jbtnAddRoomInfo.setText("Update Subject Information");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfNoofChair = new javax.swing.JTextField();
        jtfRoomID = new javax.swing.JTextField();
        jtfRoomName = new javax.swing.JTextField();
        jbtnAddRoomInfo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Room Info");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Enter No of Chairs:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 190, 160, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Enter Room ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 32, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Enter Room Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 110, 160, 30);
        getContentPane().add(jtfNoofChair);
        jtfNoofChair.setBounds(250, 190, 370, 40);
        getContentPane().add(jtfRoomID);
        jtfRoomID.setBounds(249, 30, 370, 40);

        jtfRoomName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfRoomNameKeyTyped(evt);
            }
        });
        getContentPane().add(jtfRoomName);
        jtfRoomName.setBounds(250, 110, 370, 40);

        jbtnAddRoomInfo.setBackground(new java.awt.Color(102, 204, 0));
        jbtnAddRoomInfo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnAddRoomInfo.setText("Add Room Info");
        jbtnAddRoomInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddRoomInfoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAddRoomInfo);
        jbtnAddRoomInfo.setBounds(170, 280, 330, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddRoomInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddRoomInfoActionPerformed
       String message = "";
        try{
            String roomid = jtfRoomID.getText().trim();
            String roomname = jtfRoomName.getText().trim();
            String noofchair = jtfNoofChair.getText().trim();
            if (Checks.isEmpty(roomid)) {
                message = "Please Enter Some Value In Room Id And Room Name(if not filled) before pressing Add Button";
                
             }else if(Checks.isEmpty(roomname)){
                 message ="Please Enter Some Value in Room Name And Room Id(if not filled)...Before pressing Add button";
             }
            else if(Checks.isNumeric(noofchair)){
                 
                  RoomInfoTO data = new RoomInfoTO();
                   data.setRoomID(roomid);
                   data.setRoomName(roomname);
                   data.setNoofChair(Integer.parseInt(noofchair));
                   RoomInfoDAO action = new RoomInfoDAO();
                   if(jbtnAddRoomInfo.getText().contains("Add")){
                   if (action.insertRecord(data)) {
                        message = "Record Is Successfully Inserted";
                    } else {
                        message = action.getErrorMessage();
                         if(message.contains("PRIMARY")){
                            message = "This RoomID Is Already In Use";
                        }
                         if(message.contains("Duplicate")){
                             message = "Hello User You Entered The Same Value For RoomID So Kindly Enter Some Other Relevant ID!";
                         }
                    }
                   }else if(jbtnAddRoomInfo.getText().contains("Update")) {
                       if (action.updateRecord(data)) {
                        message = "Record Is Successfully Updated";
                    } else {
                        message = action.getErrorMessage();
                    }
                     JOptionPane.showMessageDialog(this, message);
                     ViewRoomInfo obj = new ViewRoomInfo();
                     obj.setVisible(true);
                     JDesktopPane jdp = getDesktopPane();
                     jdp.add(obj);
                     try {
                         obj.setSelected(true);
                     }catch (PropertyVetoException ex) {       
                     }
                     dispose();
                   }
             }else{
                  message = "Please Enter Some Numeric Value In No Of Chair Box";
             
          }
            
        }catch(Exception ex){
         message = ex.getMessage();
        }
        JOptionPane.showMessageDialog(this, message);
        
    }//GEN-LAST:event_jbtnAddRoomInfoActionPerformed

    private void jtfRoomNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfRoomNameKeyTyped
        if(Character.isLetter(evt.getKeyChar())|| evt.getKeyChar()==' '){
            
        }else{
            evt.consume();
            try{
                
            }catch(Exception ex){
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jtfRoomNameKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnAddRoomInfo;
    private javax.swing.JTextField jtfNoofChair;
    private javax.swing.JTextField jtfRoomID;
    private javax.swing.JTextField jtfRoomName;
    // End of variables declaration//GEN-END:variables
}
