/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package admin.ui;

import Operational.Checks;
import javax.swing.JOptionPane;
import model.dao.LoginInfoDAO;
import model.to.LoginInfoTO;

/**
 *
 * @author vijay
 */
public class LoginScreen extends javax.swing.JFrame {

    int counter;
    
    public LoginScreen() {
        initComponents();
        setSize(684,436);
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnLogin);
        //getContentPane().setBackground(Color.LIGHT_GRAY);
        counter=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfUserName = new javax.swing.JTextField();
        jtfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Screen");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Enter Password:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 150, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Enter User Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 52, 150, 30);

        jtfUserName.setAutoscrolls(false);
        getContentPane().add(jtfUserName);
        jtfUserName.setBounds(280, 50, 270, 40);
        getContentPane().add(jtfPassword);
        jtfPassword.setBounds(280, 150, 270, 40);

        btnLogin.setBackground(new java.awt.Color(102, 102, 0));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(180, 250, 320, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String message = "";
        try {
            counter++;
            if (counter > 3) {
                message = " You Are Out of Attempts Sorry to leave you here!";
                dispose();
            } else {
                String username = jtfUserName.getText().trim();
                String password = new String(jtfPassword.getPassword());
                if (Checks.isEmpty(username) || Checks.isEmpty(password)) {
                    message = "Please Fill All Boxes";
                } else {
                    LoginInfoTO data = new LoginInfoDAO().checkLogin(username, password);
                    if (data != null) {
                        message = "Welcome Valid User!";
                        if (data.getRoleName().equalsIgnoreCase("admin")) {
                            MainScreen obj = new MainScreen();
                            obj.setVisible(true);
                            dispose();
                        } else if (data.getRoleName().equalsIgnoreCase("user")) {
                            user.ui.MainScreen obj = new user.ui.MainScreen();
                            obj.setVisible(true);
                            dispose();
                        }
                    } else {
                        message = "Invalid User Name And password.Please check as admin data might have been flushed off."
                                + "So Please First Enter Some Username and Password.";
                    }
                }
            }
        } catch (Exception ex) {
            message = ex.getMessage();
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jtfPassword;
    private javax.swing.JTextField jtfUserName;
    // End of variables declaration//GEN-END:variables
}
