/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package admin.ui;

import java.beans.PropertyVetoException;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;


/**
 *
 * @author vijay
 */
public class MainScreen extends javax.swing.JFrame {

    
    public MainScreen() {
        setIconImage(new ImageIcon(getClass().getResource("/admin/ui/timetable.png")).getImage());
        initComponents();
        
        setSize(700, 700);
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myDesktopPane = new admin.ui.MyDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jmiAddLoginInfo = new javax.swing.JMenuItem();
        jmiViewLoginInfo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiAddSubject = new javax.swing.JMenuItem();
        jmiViewSubject = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiAddRoomInfo = new javax.swing.JMenuItem();
        jmiViewRoomInfo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiAddFacultyInfo = new javax.swing.JMenuItem();
        jmiViewFacultyInfo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiAddFacultySubject = new javax.swing.JMenuItem();
        jmiViewFacultySubject = new javax.swing.JMenuItem();
        jmiSearchFacultySubject = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiAddRoomAllocationInfo = new javax.swing.JMenuItem();
        jmiViewRoomAllocationInfo = new javax.swing.JMenuItem();
        jmiSeachRoomAllocationInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(myDesktopPane, java.awt.BorderLayout.CENTER);

        jMenu6.setText("Login Information                                   ");

        jmiAddLoginInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/loginadd.png"))); // NOI18N
        jmiAddLoginInfo.setText("Add Login Info");
        jmiAddLoginInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddLoginInfoActionPerformed(evt);
            }
        });
        jMenu6.add(jmiAddLoginInfo);

        jmiViewLoginInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/loginview.png"))); // NOI18N
        jmiViewLoginInfo.setText("View Login Info");
        jmiViewLoginInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewLoginInfoActionPerformed(evt);
            }
        });
        jMenu6.add(jmiViewLoginInfo);

        jMenuBar2.add(jMenu6);

        jMenu1.setText("Subject Information                                    ");

        jmiAddSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/Subjectinfo.png"))); // NOI18N
        jmiAddSubject.setText("Add Subject Info");
        jmiAddSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddSubjectActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAddSubject);

        jmiViewSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/SubjectView.png"))); // NOI18N
        jmiViewSubject.setText("View Subject Info");
        jmiViewSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewSubjectActionPerformed(evt);
            }
        });
        jMenu1.add(jmiViewSubject);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Room Information                                  ");

        jmiAddRoomInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/roominfo.png"))); // NOI18N
        jmiAddRoomInfo.setText("Add Room Info");
        jmiAddRoomInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddRoomInfoActionPerformed(evt);
            }
        });
        jMenu2.add(jmiAddRoomInfo);

        jmiViewRoomInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/roomview.png"))); // NOI18N
        jmiViewRoomInfo.setText("View Room Info");
        jmiViewRoomInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewRoomInfoActionPerformed(evt);
            }
        });
        jMenu2.add(jmiViewRoomInfo);

        jMenuBar2.add(jMenu2);

        jMenu3.setText("Faculty Information                                        ");

        jmiAddFacultyInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/facultyinfo.png"))); // NOI18N
        jmiAddFacultyInfo.setText("Add Faculty Info");
        jmiAddFacultyInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddFacultyInfoActionPerformed(evt);
            }
        });
        jMenu3.add(jmiAddFacultyInfo);

        jmiViewFacultyInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/facultyview.png"))); // NOI18N
        jmiViewFacultyInfo.setText("View Faculty Info");
        jmiViewFacultyInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewFacultyInfoActionPerformed(evt);
            }
        });
        jMenu3.add(jmiViewFacultyInfo);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Faculty Subject                                   ");

        jmiAddFacultySubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/facultysubjectinfo.png"))); // NOI18N
        jmiAddFacultySubject.setText("Add FacultySubject");
        jmiAddFacultySubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddFacultySubjectActionPerformed(evt);
            }
        });
        jMenu4.add(jmiAddFacultySubject);

        jmiViewFacultySubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/facultysubjectview.png"))); // NOI18N
        jmiViewFacultySubject.setText("View Faculty Subject");
        jmiViewFacultySubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewFacultySubjectActionPerformed(evt);
            }
        });
        jMenu4.add(jmiViewFacultySubject);

        jmiSearchFacultySubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/facultysubjectsearch.png"))); // NOI18N
        jmiSearchFacultySubject.setText("Search Faculty Subject");
        jmiSearchFacultySubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSearchFacultySubjectActionPerformed(evt);
            }
        });
        jMenu4.add(jmiSearchFacultySubject);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Room Allocation                                       ");

        jmiAddRoomAllocationInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/roomallocationadd.png"))); // NOI18N
        jmiAddRoomAllocationInfo.setText("Add Room Allocation Info");
        jmiAddRoomAllocationInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddRoomAllocationInfoActionPerformed(evt);
            }
        });
        jMenu5.add(jmiAddRoomAllocationInfo);

        jmiViewRoomAllocationInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/roomallocationview.PNG"))); // NOI18N
        jmiViewRoomAllocationInfo.setText("View Room Allocation Info");
        jmiViewRoomAllocationInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewRoomAllocationInfoActionPerformed(evt);
            }
        });
        jMenu5.add(jmiViewRoomAllocationInfo);

        jmiSeachRoomAllocationInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/facultysubjectsearch.png"))); // NOI18N
        jmiSeachRoomAllocationInfo.setText("Search Room Allocation Info");
        jmiSeachRoomAllocationInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSeachRoomAllocationInfoActionPerformed(evt);
            }
        });
        jMenu5.add(jmiSeachRoomAllocationInfo);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAddSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddSubjectActionPerformed
       /* AddSubjectInfo obj = new AddSubjectInfo();
        obj.setVisible(true);
         myDesktopPane.add(obj);
        try {
            obj.setSelected(true);
        } catch(PropertyVetoException ex) {
        }*/
        displayScreen(new AddSubjectInfo());
    }//GEN-LAST:event_jmiAddSubjectActionPerformed

    private void jmiViewSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewSubjectActionPerformed
       /* ViewSubjectInfo obj = new ViewSubjectInfo();
        obj.setVisible(true);
        myDesktopPane.add(obj);
        try {
            obj.setSelected(true);
        } catch(PropertyVetoException ex) {
        }*/
        displayScreen(new ViewSubjectInfo());
    }//GEN-LAST:event_jmiViewSubjectActionPerformed

    private void jmiAddRoomInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddRoomInfoActionPerformed
       /* AddRoomInfo obj = new AddRoomInfo();
        obj.setVisible(true);
        myDesktopPane.add(obj);
        try {
            obj.setSelected(true);
        } catch(PropertyVetoException ex) {
        }*/
        displayScreen(new AddRoomInfo());
    }//GEN-LAST:event_jmiAddRoomInfoActionPerformed

    private void jmiViewRoomInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewRoomInfoActionPerformed
      /*   ViewRoomInfo obj = new ViewRoomInfo();
        obj.setVisible(true);
        myDesktopPane.add(obj);
        try {
            obj.setSelected(true);
        } catch(PropertyVetoException ex) {
        } */
        displayScreen(new ViewRoomInfo());
    }//GEN-LAST:event_jmiViewRoomInfoActionPerformed

    private void jmiAddFacultyInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddFacultyInfoActionPerformed
       /*  AddFacultyInfo obj = new AddFacultyInfo();
        obj.setVisible(true);
        myDesktopPane.add(obj);
        try {
            obj.setSelected(true);
        } catch(PropertyVetoException ex) {
        }*/
        displayScreen(new AddFacultyInfo());
    }//GEN-LAST:event_jmiAddFacultyInfoActionPerformed

    private void jmiViewFacultyInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewFacultyInfoActionPerformed
       /* ViewFacultyInfo obj = new ViewFacultyInfo();
        obj.setVisible(true);
        myDesktopPane.add(obj);
        try {
            obj.setSelected(true);
        } catch(PropertyVetoException ex) {
        }*/
        displayScreen(new ViewFacultyInfo());
    }//GEN-LAST:event_jmiViewFacultyInfoActionPerformed

    private void jmiAddFacultySubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddFacultySubjectActionPerformed
       /* AddFacultySubject obj = new AddFacultySubject();
        obj.setVisible(true);
        myDesktopPane.add(obj);
        try {
            obj.setSelected(true);
        } catch(PropertyVetoException ex) {
        }*/
        displayScreen(new AddFacultySubject());
    }//GEN-LAST:event_jmiAddFacultySubjectActionPerformed

    private void jmiViewFacultySubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewFacultySubjectActionPerformed
       /* ViewFacultySubject obj = new ViewFacultySubject();
        obj.setVisible(true);
        myDesktopPane.add(obj);
        try {
            obj.setSelected(true);
        } catch(PropertyVetoException ex) {
        }*/
        displayScreen(new ViewFacultySubject());
    }//GEN-LAST:event_jmiViewFacultySubjectActionPerformed

    private void jmiAddRoomAllocationInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddRoomAllocationInfoActionPerformed
       /*  AddRoomAllocation obj = new AddRoomAllocation();
        obj.setVisible(true);
        myDesktopPane.add(obj);
        try {
            obj.setSelected(true);
        } catch(PropertyVetoException ex) {
        }*/
        displayScreen(new AddRoomAllocation());
    }//GEN-LAST:event_jmiAddRoomAllocationInfoActionPerformed

    private void jmiViewRoomAllocationInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewRoomAllocationInfoActionPerformed
       /*  ViewRoomAllocation obj = new ViewRoomAllocation();
        obj.setVisible(true);
        myDesktopPane.add(obj);
        try {
            obj.setSelected(true);
        } catch(PropertyVetoException ex) {
        }*/
        displayScreen(new ViewRoomAllocation());
    }//GEN-LAST:event_jmiViewRoomAllocationInfoActionPerformed

    private void jmiAddLoginInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddLoginInfoActionPerformed
       /* AddLoginInfo obj = new AddLoginInfo();
        obj.setVisible(true);
        myDesktopPane.add(obj);
        try {
            obj.setSelected(true);
        } catch(PropertyVetoException ex) {
        }*/
        displayScreen(new AddLoginInfo());
    }//GEN-LAST:event_jmiAddLoginInfoActionPerformed

    private void jmiViewLoginInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewLoginInfoActionPerformed
       /*  ViewLoginInfo obj = new ViewLoginInfo();
        obj.setVisible(true);
        myDesktopPane.add(obj);
        try {
            obj.setSelected(true);
        } catch(PropertyVetoException ex) {
        }*/
        displayScreen(new ViewLoginInfo());
    }//GEN-LAST:event_jmiViewLoginInfoActionPerformed

    private void jmiSearchFacultySubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSearchFacultySubjectActionPerformed
       /*  SearchFacultySubject obj = new SearchFacultySubject();
        obj.setVisible(true);
        myDesktopPane.add(obj);
        try {
            obj.setSelected(true);
        } catch(PropertyVetoException ex) {
        }*/
        displayScreen(new SearchFacultySubject());
    }//GEN-LAST:event_jmiSearchFacultySubjectActionPerformed

    private void jmiSeachRoomAllocationInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSeachRoomAllocationInfoActionPerformed
        /* SearchRoomAllocation obj = new SearchRoomAllocation();
        obj.setVisible(true);
        myDesktopPane.add(obj);
        try {
            obj.setSelected(true);
        } catch(PropertyVetoException ex) {
        }*/
        displayScreen(new SearchRoomAllocation());
    }//GEN-LAST:event_jmiSeachRoomAllocationInfoActionPerformed
 
    private void displayScreen(JInternalFrame obj){
         obj.setVisible(true);
        myDesktopPane.add(obj);
        try {
            obj.setSelected(true);
        } catch(PropertyVetoException ex) {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jmiAddFacultyInfo;
    private javax.swing.JMenuItem jmiAddFacultySubject;
    private javax.swing.JMenuItem jmiAddLoginInfo;
    private javax.swing.JMenuItem jmiAddRoomAllocationInfo;
    private javax.swing.JMenuItem jmiAddRoomInfo;
    private javax.swing.JMenuItem jmiAddSubject;
    private javax.swing.JMenuItem jmiSeachRoomAllocationInfo;
    private javax.swing.JMenuItem jmiSearchFacultySubject;
    private javax.swing.JMenuItem jmiViewFacultyInfo;
    private javax.swing.JMenuItem jmiViewFacultySubject;
    private javax.swing.JMenuItem jmiViewLoginInfo;
    private javax.swing.JMenuItem jmiViewRoomAllocationInfo;
    private javax.swing.JMenuItem jmiViewRoomInfo;
    private javax.swing.JMenuItem jmiViewSubject;
    private admin.ui.MyDesktopPane myDesktopPane;
    // End of variables declaration//GEN-END:variables
}
