/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package admin.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.dao.FacultySubjectDAO;
import model.to.FacultySubjectTO;

/**
 *
 * @author vijay
 */
public class ViewFacultySubject extends javax.swing.JInternalFrame {

    ArrayList<FacultySubjectTO> allFacultySubjectdata;
    int row;
    JPopupMenu jpopup;
    
    public ViewFacultySubject() {
        initComponents();
        setSize(600,600);
        bindTableData();
        row=-1;
        jpopup = new JPopupMenu();
        JMenuItem jmiUpdate = new JMenuItem("Update This Record");
        jpopup.add(jmiUpdate);
        JMenuItem jmiDelete = new JMenuItem("Delete This Record");
        jpopup.add(jmiDelete);
         jmiUpdate.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                updateRecord();
            }
        });
         
         jmiDelete.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
            }
        });
    }
    
      private void deleteRecord(){
          if (row != -1) {
            FacultySubjectTO fst = allFacultySubjectdata.get(row);
            if (fst != null) {
                int result = JOptionPane.showConfirmDialog(this, "Are You Sure To Delete This Information?", "Message From Admin", JOptionPane.OK_CANCEL_OPTION);
                if (result == JOptionPane.OK_OPTION) {
                    FacultySubjectDAO action = new FacultySubjectDAO();
                    if (action.deleteRecord(fst.getSrNo())) {
                        JOptionPane.showMessageDialog(this, "Record is Deleted");
                        bindTableData();
                        row = -1;
                    } else {
                        JOptionPane.showMessageDialog(this, action.getErrorMessage());
                    }
                }
            }
        }
      }  
    
      private void updateRecord(){
        if(row!=-1){
            FacultySubjectTO data = allFacultySubjectdata.get(row);
            if(data!=null){
                AddFacultySubject obj = new AddFacultySubject(data);
                obj.setVisible(true);
                 obj.setTitle("Update Faculty Info");
                JDesktopPane jdp = getDesktopPane();
                jdp.add(obj);
                try {
                    obj.setSelected(true);
                } catch (PropertyVetoException ex) {
                }
                dispose();
            }
        }
      }
      private void bindTableData() {
          
          allFacultySubjectdata = new FacultySubjectDAO().getAllRecord();
          if (allFacultySubjectdata != null && allFacultySubjectdata.size() != 0) {
            int totalRows = allFacultySubjectdata.size();
            String[] columnNames = {" Faculty Name ", " Subject Name ", " IsCurrent "};
            Object allData[][] = new Object[totalRows][columnNames.length];
            for (int i = 0; i < totalRows; i++) {
                FacultySubjectTO cit = allFacultySubjectdata.get(i);
                allData[i] = new Object[columnNames.length];
                allData[i][0] = cit.getFacultyName();
                allData[i][1] = cit.getSubjectName();
                allData[i][2] = cit.getIsCurrent();
            }
            DefaultTableModel dtm = new DefaultTableModel(allData, columnNames);
            jtFacultySubject.setModel(dtm);
        }
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtFacultySubject = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("View Faculty Subject");

        jtFacultySubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtFacultySubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFacultySubjectMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtFacultySubject);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtFacultySubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFacultySubjectMouseClicked
         //if(evt.getButton()== MouseEvent.BUTTON3){
        if (SwingUtilities.isRightMouseButton(evt)) {
            //System.out.println(" Right Button is Clicked ");
            int idx = jtFacultySubject.rowAtPoint(evt.getPoint());
            jtFacultySubject.getSelectionModel().setSelectionInterval(idx, idx);
            row = jtFacultySubject.getSelectedRow();
            //System.out.println(row);
            jpopup.show(jtFacultySubject, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jtFacultySubjectMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtFacultySubject;
    // End of variables declaration//GEN-END:variables
}
